[workspace]

members = [
    "cosmic-panel-bin",
    "cosmic-panel-config"
]


[patch.crates-io]
wayland-protocols-wlr = { git = "https://github.com/smithay/wayland-rs", rev = "746c68154d35763025877c9713a30c2b35232f8c"  }
wayland-protocols-misc = { git = "https://github.com/smithay/wayland-rs", rev = "746c68154d35763025877c9713a30c2b35232f8c"  }
wayland-egl = { git = "https://github.com/smithay/wayland-rs", rev = "746c68154d35763025877c9713a30c2b35232f8c"  }
wayland-protocols = { git = "https://github.com/smithay/wayland-rs", rev = "746c68154d35763025877c9713a30c2b35232f8c"  }
wayland-server = { git = "https://github.com/smithay/wayland-rs", rev = "746c68154d35763025877c9713a30c2b35232f8c"  }
wayland-sys = { git = "https://github.com/smithay/wayland-rs", rev = "746c68154d35763025877c9713a30c2b35232f8c"  }
wayland-backend = { git = "https://github.com/smithay/wayland-rs", rev = "746c68154d35763025877c9713a30c2b35232f8c"  }
wayland-scanner = { git = "https://github.com/smithay/wayland-rs", rev = "746c68154d35763025877c9713a30c2b35232f8c"  }
wayland-cursor = { git = "https://github.com/smithay/wayland-rs", rev = "746c68154d35763025877c9713a30c2b35232f8c"  }
wayland-client = { git = "https://github.com/smithay/wayland-rs", rev = "746c68154d35763025877c9713a30c2b35232f8c"  }

[profile.release]
incremental = true
debug = 1

