[package]
name = "cosmic-dock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cascade = "1.0.0"
gtk4 = { version = "0.4.4", features = ["v4_4"] }
gtk4-sys = "0.4.2"
glib-sys = "0.15.1"
gdk4 = "0.4.4"
gdk4-wayland = { version = "0.4.2", features = [ "wayland_crate" ], optional = true }
gdk4-x11 = { version = "0.4.2", features = [ "xlib" ] }
gio = "0.15.2"
gobject-sys = "0.15.1"
wayland-client = { version = "0.29.4", optional = true }
wayland-protocols = { version = "0.29.4", features = [ "client", "unstable_protocols" ], optional = true }
libcosmic = { git = "https://github.com/pop-os/libcosmic" }
relm4-macros = { git = "https://github.com/AaronErhardt/Relm4" }
serde = "1.0.134"
serde_json = "1.0.75"
tokio = { version = "1.15.0", features = ["sync"] }
futures = "0.3.19"
futures-util = "0.3.19"
once_cell = "1.9.0"
xdg = "2.4.0"
zbus = "2.0.1"
zvariant = "3.1.0"
zvariant_derive = "3.1.0"
libloading = "0.7.3"
cosmic-plugin = { git = "https://github.com/wash2/dock-plugin" }

[profile.release]
incremental = true
debug = 1

[features]
layer-shell = ["gdk4-wayland", "wayland-client", "wayland-protocols"]
