[package]
name = "cosmic-panel-config"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = []

[dependencies]
anyhow = "1.0.53"
ron = "0.7.0"
serde = { version = "1.0.136", features = ["derive"] }
xdg = "2.4.0"
sctk = { package = "smithay-client-toolkit", git = "https://github.com/wash2/client-toolkit.git", default-features = false, features = ["calloop"] }
gtk4 = { version = "0.4.5", features = ["v4_4"], optional = true }
slog = { version = "2.7.0", features = ["max_level_trace", "release_max_level_warn"] }
xdg-shell-wrapper = { path = "../../xdg-shell-wrapper" }

